---

- name: Installation of rabbitmq
  apt:
    name: rabbitmq-server

- name: Add openstack user
  rabbitmq_user:
    user: openstack
    password: '{{ RabbitMq_pass }}'
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present

- name: Permit configuration, write, and read access for the openstack user
  shell: rabbitmqctl set_permissions openstack ".*" ".*" ".*"

