- name: Enable the repository for Ubuntu Cloud Archive
  become : yes
  become_user: root
  apt:
    pkg: ['software-properties-common', 'ubuntu-cloud-keyring']
    state: present
- name: Adding cloud archive repository
  apt_repository:
    repo: 'deb http://ubuntu-cloud.archive.canonical.com/ubuntu xenial-updates/queens main'
      state: present
      update_cache: yes
- name: Finalize the installation
  apt:
    update_cache: yes
- name: Perform dist upgrade
  apt:
    upgrade: dist
- name: Check if reboot is required
  stat:
    path: /var/run/reboot-required
    register: reboot_required_file
- name: reboot if required
  shell: reboot
  when: reboot_required_file.stat.exists == true

- name: Waiting for the machine to come back
  local_action: wait_for host={{ ansible_host }} state=started port=22 delay=30
  become: yes
  when: reboot_required_file.stat.exists == false

- name: Install openstack client
  apt:
    name: python-openstackclient
    state: present

