---
- name: Install etcd packages
  apt: name=etcd state=present

- name: Edit the etcd file
  blockinfile:
    path: /etc/default/etcd
    block: |
      ETCD_NAME="controller"
      ETCD_DATA_DIR="/var/lib/etcd"
      ETCD_INITIAL_CLUSTER_STATE="new"
      ETCD_INITIAL_CLUSTER_TOKEN="etcd-cluster-01"
      ETCD_INITIAL_CLUSTER="controller=http://172.16.50.14:2380"
      ETCD_INITIAL_ADVERTISE_PEER_URLS="http://172.16.50.14:2380"
      ETCD_ADVERTISE_CLIENT_URLS="http://172.16.50.14:2379"
      ETCD_LISTEN_PEER_URLS="http://0.0.0.0:2380"
      ETCD_LISTEN_CLIENT_URLS="http://172.16.50.14:2379"

- name: Enable and start etcd service
  systemd: name=etcd enabled=true

- name: Start etcd service
  systemd: name=etcd state=started

