---

- name: Install the packages
  apt: package={{ item }} state=installed force=yes update_cache=yes cache_valid_time=300
  with_items:
    - memcached
    - python-memcache

- name: edit memcached.conf file
  replace:
    path: /etc/memcached.conf
    after: '-l '
    regexp: '^127\.0\.0\.1'
    replace: 172.16.50.14

- name: restart the service
  service: name=memcached state=restarted

